DB/WebLayer/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BusinessLogic;
using WebLayer.Models;

namespace WebLayer.Controllers
{
    public class CrudController : Controller
    {
        private IMapper mapper;
        private ILogic logic;
        private CrudModel model;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            mapper = DTO.AutoMapperConfig.GetMapper();

            logic = new RealLogic();
            model = new CrudModel();
            model.EditObject = new DeptModel();

            var dblist = logic.GetDepartments();
            model.List = mapper.Map<IQueryable<Data.DEPT>, List<Models.DeptModel>>(dblist);

            base.OnActionExecuting(filterContext);
        }

        private DeptModel GetDeptModel(int id)
        {
            Data.DEPT d = logic.GetOneDept(id);
            return mapper.Map<Data.DEPT, Models.DeptModel>(d);
        }

        // GET: Crud
        public ActionResult Index()
        {
            ViewData["TargetAction"] = "AddNew";

            return View("CrudIndex", model);
        }

        public ActionResult Details(int id)
        {
            return View("CrudDatasheet", GetDeptModel(id));
        }
        //a controller az csak egy kicsi kontroller: Skinny Controller
        //van olyan is, hogy Fat Model & Skinny Controller

        public ActionResult Edit(int id)
        {
            ViewData["TargetAction"] = "Edit";
            model.EditObject = GetDeptModel(id);
            return View("CrudIndex", model);
        }

        [HttpPost]
        public ActionResult Edit(DeptModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                logic.ModifyDept(model.deptno, model.dname, model.loc);
                TempData["result"] = "Edit OK";
            }
            else
            {
                TempData["result"] = "Edit FAIL";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddNew(DeptModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                Data.DEPT d = mapper.Map<Models.DeptModel, Data.DEPT>(model);
                d.DEPTNO = logic.GetNextDeptno();
                logic.AddDept(d);
                TempData["result"] = "Add OK";
            }
            else
            {
                TempData["result"] = "Add FAIL";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            try
            {
                logic.DelDept(id);
                TempData["result"] = "Del OK";
            }
            catch (DbUpdateException)
            {
                TempData["result"] = "Del FAIL";
            }
            catch (ArgumentException)
            {
                TempData["result"] = "Del FAIL";
            }
            return RedirectToAction("Index");
        }
    }
}

DB/WebLayer/Views/Crud/CrudDatasheet.cshtml
@model WebLayer.Models.DeptModel

@{
    ViewBag.Title = "CrudDatasheet";
}

<h2>CrudDatasheet</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.deptno)</td>
        <td>@Html.DisplayFor(m => m.deptno)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.dname)</td>
        <td>@Html.DisplayFor(m => m.dname)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.loc)</td>
        <td>@Html.DisplayFor(m => m.loc)</td>
    </tr>
</table>
    

DB/WebLayer/Views/Crud/CrudEdit.cshtml
@model WebLayer.Models.DeptModel
    


<h2>Add/Edit Department</h2>

@using (Html.BeginForm(ViewData["TargetAction"].ToString(), "Crud"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.deptno)

    <div class="editor-label">@Html.LabelFor(m => m.dname)</div>
    <div class="editor-field">@Html.EditorFor(m => m.dname)</div>

    <div class="editor-label">@Html.LabelFor(m => m.loc)</div>
    <div class="editor-field">@Html.EditorFor(m => m.loc)</div>

    <input type="submit" value="SEND" />
}

DB/WebLayer/Views/Crud/CrudIndex.cshtml
@model WebLayer.Models.CrudModel

@{
    ViewBag.Title = "CrudIndex";
}

<h2>CrudIndex</h2>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

<!-- ez a fő nézet, és kettő al nézetet fog összerakni-->
<!-- az első paraméter a nézet neve, a másik a nézet amit át akarok adni -->
@Html.Partial("CrudEdit", Model.EditObject)

@Html.Partial("CrudList", Model.List)

DB/WebLayer/Views/Crud/CrudList.cshtml
@model IEnumerable<WebLayer.Models.DeptModel>
    
<p style="color:red">@TempData["result"]</p>

@if (Model.Count() == 0)
{
    <p>No data in DB!</p>
}
else
{
    <table>
        <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.deptno)</th>
            <th>@Html.DisplayNameFor(m => m.dname)</th>
            <th>@Html.DisplayNameFor(m => m.loc)</th>
            <th>Datasheet</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.deptno)</td>
                    <td>@Html.DisplayFor(m => item.dname)</td>
                    <td>@Html.DisplayFor(m => item.loc)</td>
                    <td>@Html.ActionLink("Details", "Details", new {id = item.deptno})</td>
                    <td>@Html.ActionLink("Edit", "Edit", new { id = item.deptno })</td>
                    <td>@Html.ActionLink("Remove", "Remove", new { id = item.deptno })</td>
                </tr>
            }
        </tbody>
    </table>
}